name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install flake8 pytest flask pymongo scikit-learn pandas numpy joblib imbalanced-learn

      - name: Lint with flake8
        run: flake8 noshow_iq/ --max-line-length=88

      - name: Run pytest
        run: pytest tests/ -v

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/noshow-iq:latest .

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/noshow-iq:latest

      - name: Trigger HF Space rebuild
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
            "https://huggingface.co/api/spaces/seharzaheer687/noshow-iq/restart"
